# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_document',
            name='docfile',
            field=models.ImageField(upload_to=''),
        ),
    ]
