# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 20:50
from __future__ import unicode_literals

import ajaximage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0002_auto_20170305_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', ajaximage.fields.AjaxImageField()),
                ('thumbnail', ajaximage.fields.AjaxImageField()),
            ],
        ),
    ]
