# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0003_kitten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitten',
        ),
    ]
