# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0004_delete_kitten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Keeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='image_document',
            name='docfile',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
