# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0006_auto_20170305_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Document',
        ),
    ]
