# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0007_delete_image_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opencv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='documents/')),
            ],
        ),
    ]
